export const PAGE_LIST = [
  "DASHBOARD",
  "TRADE_METRICS",
  // "SHEET_INTEGRATION",
  "CALENDAR",
  "SETUP_RULES",
  "CAPTURED_STRATEGIES",
  "STRATEGY_ANALYSIS",
  "MISTAKES",
  "RISK_MANAGEMENT",
  "INTEGRATIONS",
  "EXTENSIONS",
];
