export const sidebarItems = [
  {
    label: "Dashboard",
    icon: "Icons/sidebar/dashboard.png",
    alt: "Dashboard",
    route: "/",
    key: "dashboard",
  },
  {
    label: "Get Trade Records",
    icon: "Icons/sidebar/edge.png",
    alt: "Find Your Edge",
    route: "/edge",
    key: "edge",
  },
  {
    label: "Monthly Overview",
    icon: "Icons/sidebar/report.png",
    alt: "Month Records",
    route: "/yearly-calendar",
    key: "yearlycalender",
  },
  {
    label: "Strategy Rules",
    icon: "Icons/sidebar/rules.png",
    alt: "Setup Rules",
    route: "/setup-rules",
    key: "setuprules",
  },
  {
    label: "Back-Tested Data",
    icon: "Icons/sidebar/tested.png",
    alt: "Back-Tested Data",
    route: "/backtest",
    key: "backtest",
  },
  {
    label: "Mistakes To Avoid",
    icon: "Icons/sidebar/cross.png",
    alt: "Mistakes To Avoid",
    route: "/mistakes",
    key: "mistakes",
  },
  {
    label: "Strategy Analysis",
    icon: "Icons/sidebar/strategy.png",
    alt: "Strategy Analysis",
    route: null,
    key: "strategyanalysis",
  },
  {
    label: "Risk Management",
    icon: "Icons/sidebar/risk-management.png",
    alt: "Risk Management",
    route: "/risk-management",
    key: "riskmanagement",
  },
];
