export const FUNCTION_TYPE = {
  SCHEMA: "SCHEMA",
  BASE: "BASE",
  WINDOW: "WINDOW",
  CONDITION: "CONDITION",
  RATIO: "RATIO",
  GLOBAL: "GLOBAL",
  NATIVE_WINDOW: "NATIVE_WINDOW",
  NATIVE_AGG: "NATIVE_AGG",
};
